name: suppnet-env
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy=1.20
  - scipy=1.6
  - matplotlib=3.4
  - pandas=1.2
  - pyside2=5.13
  - tensorflow=2.4
  - notebook=6.3