# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sat Jun  5 21:40:43 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(846, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slider_value = QtWidgets.QLabel(self.frame)
        self.slider_value.setMinimumSize(QtCore.QSize(20, 0))
        self.slider_value.setObjectName("slider_value")
        self.horizontalLayout.addWidget(self.slider_value)
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.update_normalization = QtWidgets.QPushButton(self.frame)
        self.update_normalization.setObjectName("update_normalization")
        self.horizontalLayout.addWidget(self.update_normalization)
        self.verticalLayout.addWidget(self.frame)
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.verticalLayout.addWidget(self.mplwindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 846, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionasdsd = QtWidgets.QAction(MainWindow)
        self.actionasdsd.setObjectName("actionasdsd")
        self.action_save_file = QtWidgets.QAction(MainWindow)
        self.action_save_file.setObjectName("action_save_file")
        self.actionOpen_spectrum = QtWidgets.QAction(MainWindow)
        self.actionOpen_spectrum.setObjectName("actionOpen_spectrum")
        self.actionSave_results = QtWidgets.QAction(MainWindow)
        self.actionSave_results.setObjectName("actionSave_results")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.action_normalize = QtWidgets.QAction(MainWindow)
        self.action_normalize.setEnabled(False)
        self.action_normalize.setObjectName("action_normalize")
        self.actionOpen_processed_spectrum = QtWidgets.QAction(MainWindow)
        self.actionOpen_processed_spectrum.setObjectName("actionOpen_processed_spectrum")
        self.actionSave_for_active_learning = QtWidgets.QAction(MainWindow)
        self.actionSave_for_active_learning.setObjectName("actionSave_for_active_learning")
        self.actionSave_normed_spectrum = QtWidgets.QAction(MainWindow)
        self.actionSave_normed_spectrum.setObjectName("actionSave_normed_spectrum")
        self.menuFile.addAction(self.actionOpen_spectrum)
        self.menuFile.addAction(self.actionSave_normed_spectrum)
        self.menuFile.addAction(self.actionSave_results)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_processed_spectrum)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.action_normalize)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SUPPNet - stellar spectrum normalisation", None, -1))
        self.slider_value.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.update_normalization.setText(QtWidgets.QApplication.translate("MainWindow", "Update Smoothing", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actionasdsd.setText(QtWidgets.QApplication.translate("MainWindow", "asdsd", None, -1))
        self.action_save_file.setText(QtWidgets.QApplication.translate("MainWindow", "save file", None, -1))
        self.actionOpen_spectrum.setText(QtWidgets.QApplication.translate("MainWindow", "Open spectrum", None, -1))
        self.actionSave_results.setText(QtWidgets.QApplication.translate("MainWindow", "Save full results", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.action_normalize.setText(QtWidgets.QApplication.translate("MainWindow", "Run SUPPNet", None, -1))
        self.actionOpen_processed_spectrum.setText(QtWidgets.QApplication.translate("MainWindow", "Open processed spectrum", None, -1))
        self.actionSave_for_active_learning.setText(QtWidgets.QApplication.translate("MainWindow", "Save for active learning", None, -1))
        self.actionSave_normed_spectrum.setText(QtWidgets.QApplication.translate("MainWindow", "Save normed spectrum", None, -1))

